package com.interviewcity.interview;

import com.interviewcity.interview.model.City;
import com.interviewcity.interview.model.Client;
import com.interviewcity.interview.repository.CityRepository;
import com.interviewcity.interview.repository.ClientRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

@SpringBootApplication
public class InterviewApplication implements ApplicationRunner {

    @Autowired
    CityRepository cityRep;

    @Autowired
    ClientRepository clientRep;

    public static void main(String[] args) {
        SpringApplication.run(InterviewApplication.class, args);
    }

    @Override
    public void run(ApplicationArguments args) throws Exception {

        cityRep.save(new City(1, "São Paulo", "SP"));
        cityRep.save(new City(2, "Guarulhos", "SP"));
        cityRep.save(new City(3, "Campinas", "SP"));
        cityRep.save(new City(4, "São Bernardo do Campo", "SP"));
        cityRep.save(new City(5, "São José dos Campos", "SP"));
        cityRep.save(new City(6, "Santo André", "SP"));
        cityRep.save(new City(7, "Ribeirão Preto", "SP"));
        cityRep.save(new City(8, "Osasco", "SP"));
        cityRep.save(new City(9, "Sorocaba", "SP"));
        cityRep.save(new City(10, "Mauá", "SP"));
        cityRep.save(new City(11, "São José do Rio Preto", "SP"));
        cityRep.save(new City(12, "Mogi das Cruzes", "SP"));
        cityRep.save(new City(13, "Santos", "SP"));
        cityRep.save(new City(14, "Diadema", "SP"));
        cityRep.save(new City(15, "Jundiaí", "SP"));
        cityRep.save(new City(16, "Piracicaba", "SP"));
        cityRep.save(new City(17, "Carapicuíba", "SP"));
        cityRep.save(new City(18, "Bauru", "SP"));
        cityRep.save(new City(19, "Itaquaquecetuba", "SP"));
        cityRep.save(new City(20, "São Vicente", "SP"));
        cityRep.save(new City(21, "Franca", "SP"));
        cityRep.save(new City(22, "Praia Grande", "SP"));
        cityRep.save(new City(23, "Guarujá", "SP"));
        cityRep.save(new City(24, "Taubaté", "SP"));
        cityRep.save(new City(25, "Limeira", "SP"));
        cityRep.save(new City(26, "Suzano", "SP"));
        cityRep.save(new City(27, "Taboão da Serra", "SP"));
        cityRep.save(new City(28, "Sumaré", "SP"));
        cityRep.save(new City(29, "Barueri", "SP"));
        cityRep.save(new City(30, "Embu das Artes", "SP"));
        cityRep.save(new City(31, "Indaiatuba", "SP"));
        cityRep.save(new City(32, "São Carlos", "SP"));
        cityRep.save(new City(33, "Cotia", "SP"));
        cityRep.save(new City(34, "Americana", "SP"));
        cityRep.save(new City(35, "Itapevi", "SP"));
        cityRep.save(new City(36, "Marília", "SP"));
        cityRep.save(new City(37, "Araraquara", "SP"));
        cityRep.save(new City(38, "Jacareí", "SP"));
        cityRep.save(new City(39, "Hortolândia", "SP"));
        cityRep.save(new City(40, "Presidente Prudente", "SP"));
        cityRep.save(new City(41, "Rio Claro", "SP"));
        cityRep.save(new City(42, "Araçatuba", "SP"));
        cityRep.save(new City(43, "Ferraz de Vasconcelos", "SP"));
        cityRep.save(new City(44, "Santa Bárbara d'Oeste", "SP"));
        cityRep.save(new City(45, "Itapecerica da Serra", "SP"));
        cityRep.save(new City(46, "Francisco Morato", "SP"));
        cityRep.save(new City(47, "Itu", "SP"));
        cityRep.save(new City(48, "Bragança Paulista", "SP"));
        cityRep.save(new City(49, "Pindamonhangaba", "SP"));
        cityRep.save(new City(50, "Itapetininga", "SP"));
        cityRep.save(new City(51, "São Caetano do Sul", "SP"));
        cityRep.save(new City(52, "Franco da Rocha", "SP"));
        cityRep.save(new City(53, "Mogi Guaçu", "SP"));
        cityRep.save(new City(54, "Jaú", "SP"));
        cityRep.save(new City(55, "Botucatu", "SP"));
        cityRep.save(new City(56, "Atibaia", "SP"));
        cityRep.save(new City(57, "Santana de Parnaíba", "SP"));
        cityRep.save(new City(58, "Araras", "SP"));
        cityRep.save(new City(59, "Cubatão", "SP"));
        cityRep.save(new City(60, "Valinhos", "SP"));
        cityRep.save(new City(61, "Sertãozinho", "SP"));
        cityRep.save(new City(62, "Jandira", "SP"));
        cityRep.save(new City(63, "Birigui", "SP"));
        cityRep.save(new City(64, "Ribeirão Pires", "SP"));
        cityRep.save(new City(65, "Votorantim", "SP"));
        cityRep.save(new City(66, "Caraguatatuba", "SP"));
        cityRep.save(new City(67, "Várzea Paulista", "SP"));
        cityRep.save(new City(68, "Tatuí", "SP"));
        cityRep.save(new City(69, "Barretos", "SP"));
        cityRep.save(new City(70, "Itatiba", "SP"));
        cityRep.save(new City(71, "Guaratinguetá", "SP"));
        cityRep.save(new City(72, "Catanduva", "SP"));
        cityRep.save(new City(73, "Salto", "SP"));
        cityRep.save(new City(74, "Poá", "SP"));
        cityRep.save(new City(75, "Ourinhos", "SP"));
        cityRep.save(new City(76, "Paulínia", "SP"));
        cityRep.save(new City(77, "Assis", "SP"));
        cityRep.save(new City(78, "Leme", "SP"));
        cityRep.save(new City(79, "Itanhaém", "SP"));
        cityRep.save(new City(80, "Caieiras", "SP"));
        cityRep.save(new City(81, "Mairiporã", "SP"));
        cityRep.save(new City(82, "Votuporanga", "SP"));
        cityRep.save(new City(83, "Caçapava", "SP"));
        cityRep.save(new City(84, "Itapeva", "SP"));
        cityRep.save(new City(85, "Mogi Mirim", "SP"));
        cityRep.save(new City(86, "São Roque", "SP"));
        cityRep.save(new City(87, "Ubatuba", "SP"));
        cityRep.save(new City(88, "São João da Boa Vista", "SP"));
        cityRep.save(new City(89, "Avaré", "SP"));
        cityRep.save(new City(90, "Arujá", "SP"));
        cityRep.save(new City(91, "São Sebastião", "SP"));
        cityRep.save(new City(92, "Lorena", "SP"));
        cityRep.save(new City(93, "Campo Limpo Paulista", "SP"));
        cityRep.save(new City(94, "Matão", "SP"));
        cityRep.save(new City(95, "Cruzeiro", "SP"));
        cityRep.save(new City(96, "Vinhedo", "SP"));
        cityRep.save(new City(97, "Ibiúna", "SP"));
        cityRep.save(new City(98, "Lins", "SP"));
        cityRep.save(new City(99, "Cajamar", "SP"));
        cityRep.save(new City(100, "Jaboticabal", "SP"));
        cityRep.save(new City(101, "Bebedouro", "SP"));
        cityRep.save(new City(102, "Pirassununga", "SP"));
        cityRep.save(new City(103, "Itapira", "SP"));
        cityRep.save(new City(104, "Cosmópolis", "SP"));
        cityRep.save(new City(105, "Amparo", "SP"));
        cityRep.save(new City(106, "Embu-Guaçu", "SP"));
        cityRep.save(new City(107, "Fernandópolis", "SP"));
        cityRep.save(new City(108, "Peruíbe", "SP"));
        cityRep.save(new City(109, "Lençóis Paulista", "SP"));
        cityRep.save(new City(110, "Mococa", "SP"));
        cityRep.save(new City(111, "Tupã", "SP"));
        cityRep.save(new City(112, "Bertioga", "SP"));
        cityRep.save(new City(113, "Penápolis", "SP"));
        cityRep.save(new City(114, "Batatais", "SP"));
        cityRep.save(new City(115, "Itupeva", "SP"));
        cityRep.save(new City(116, "Boituva", "SP"));
        cityRep.save(new City(117, "Nova Odessa", "SP"));
        cityRep.save(new City(118, "Monte Mor", "SP"));
        cityRep.save(new City(119, "Ibitinga", "SP"));
        cityRep.save(new City(120, "Mirassol", "SP"));
        cityRep.save(new City(121, "Jaguariúna", "SP"));
        cityRep.save(new City(122, "Santa Isabel", "SP"));
        cityRep.save(new City(123, "Mongaguá", "SP"));
        cityRep.save(new City(124, "Taquaritinga", "SP"));
        cityRep.save(new City(125, "Andradina", "SP"));
        cityRep.save(new City(126, "Porto Ferreira", "SP"));
        cityRep.save(new City(127, "Registro", "SP"));
        cityRep.save(new City(128, "Capivari", "SP"));
        cityRep.save(new City(129, "Piedade", "SP"));
        cityRep.save(new City(130, "Artur Nogueira", "SP"));
        cityRep.save(new City(131, "Olímpia", "SP"));
        cityRep.save(new City(132, "São José do Rio Pardo", "SP"));
        cityRep.save(new City(133, "Vargem Grande Paulista", "SP"));
        cityRep.save(new City(134, "Porto Feliz", "SP"));
        cityRep.save(new City(135, "Campos do Jordão", "SP"));
        cityRep.save(new City(136, "São Joaquim da Barra", "SP"));
        cityRep.save(new City(137, "Rio Grande da Serra", "SP"));
        cityRep.save(new City(138, "Pontal", "SP"));
        cityRep.save(new City(139, "Monte Alto", "SP"));
        cityRep.save(new City(140, "Itararé", "SP"));
        cityRep.save(new City(141, "Cabreúva", "SP"));
        cityRep.save(new City(142, "Louveira", "SP"));
        cityRep.save(new City(143, "Cerquilho", "SP"));
        cityRep.save(new City(144, "Jales", "SP"));
        cityRep.save(new City(145, "Pedreira", "SP"));
        cityRep.save(new City(146, "Santa Cruz do Rio Pardo", "SP"));
        cityRep.save(new City(147, "Tremembé", "SP"));
        cityRep.save(new City(148, "Mairinque", "SP"));
        cityRep.save(new City(149, "Capão Bonito", "SP"));
        cityRep.save(new City(150, "Pederneiras", "SP"));
        cityRep.save(new City(151, "Dracena", "SP"));
        cityRep.save(new City(152, "Paraguaçu Paulista", "SP"));
        cityRep.save(new City(153, "Salto de Pirapora", "SP"));
        cityRep.save(new City(154, "Serrana", "SP"));
        cityRep.save(new City(155, "Jardinópolis", "SP"));
        cityRep.save(new City(156, "Espírito Santo do Pinhal", "SP"));
        cityRep.save(new City(157, "Garça", "SP"));
        cityRep.save(new City(158, "Presidente Epitácio", "SP"));
        cityRep.save(new City(159, "Orlândia", "SP"));
        cityRep.save(new City(160, "Itápolis", "SP"));
        cityRep.save(new City(161, "Vargem Grande do Sul", "SP"));
        cityRep.save(new City(162, "Tietê", "SP"));
        cityRep.save(new City(163, "Ituverava", "SP"));
        cityRep.save(new City(164, "Novo Horizonte", "SP"));
        cityRep.save(new City(165, "Socorro", "SP"));
        cityRep.save(new City(166, "São Manuel", "SP"));
        cityRep.save(new City(167, "Guaíra", "SP"));
        cityRep.save(new City(168, "Américo Brasiliense", "SP"));
        cityRep.save(new City(169, "Promissão", "SP"));
        cityRep.save(new City(170, "Guariba", "SP"));
        cityRep.save(new City(171, "Pitangueiras", "SP"));
        cityRep.save(new City(172, "Presidente Venceslau", "SP"));
        cityRep.save(new City(173, "Iperó", "SP"));
        cityRep.save(new City(174, "Agudos", "SP"));
        cityRep.save(new City(175, "José Bonifácio", "SP"));
        cityRep.save(new City(176, "Aguaí", "SP"));
        cityRep.save(new City(177, "Aparecida", "SP"));
        cityRep.save(new City(178, "Barra Bonita", "SP"));
        cityRep.save(new City(179, "São Pedro", "SP"));
        cityRep.save(new City(180, "Rio das Pedras", "SP"));
        cityRep.save(new City(181, "Ilhabela", "SP"));
        cityRep.save(new City(182, "Cravinhos", "SP"));
        cityRep.save(new City(183, "Bariri", "SP"));
        cityRep.save(new City(184, "Ibaté", "SP"));
        cityRep.save(new City(185, "Adamantina", "SP"));
        cityRep.save(new City(186, "Araçoiaba da Serra", "SP"));
        cityRep.save(new City(187, "Santa Cruz das Palmeiras", "SP"));
        cityRep.save(new City(188, "Descalvado", "SP"));
        cityRep.save(new City(189, "Cachoeira Paulista", "SP"));
        cityRep.save(new City(190, "Morro Agudo", "SP"));
        cityRep.save(new City(191, "Barrinha", "SP"));
        cityRep.save(new City(192, "Guararapes", "SP"));
        cityRep.save(new City(193, "São Miguel Arcanjo", "SP"));
        cityRep.save(new City(194, "Osvaldo Cruz", "SP"));
        cityRep.save(new City(195, "Biritiba Mirim", "SP"));
        cityRep.save(new City(196, "Santa Fé do Sul", "SP"));
        cityRep.save(new City(197, "Juquitiba", "SP"));
        cityRep.save(new City(198, "Cândido Mota", "SP"));
        cityRep.save(new City(199, "Iguape", "SP"));
        cityRep.save(new City(200, "Jarinu", "SP"));
        cityRep.save(new City(201, "Igarapava", "SP"));
        cityRep.save(new City(202, "Casa Branca", "SP"));
        cityRep.save(new City(203, "Guararema", "SP"));
        cityRep.save(new City(204, "Piraju", "SP"));
        cityRep.save(new City(205, "Rancharia", "SP"));
        cityRep.save(new City(206, "Mirandópolis", "SP"));
        cityRep.save(new City(207, "Serra Negra", "SP"));
        cityRep.save(new City(208, "Pilar do Sul", "SP"));
        cityRep.save(new City(209, "Laranjal Paulista", "SP"));
        cityRep.save(new City(210, "Cajati", "SP"));
        cityRep.save(new City(211, "Conchal", "SP"));
        cityRep.save(new City(212, "Pirapozinho", "SP"));
        cityRep.save(new City(213, "Santa Rita do Passa Quatro", "SP"));
        cityRep.save(new City(214, "Dois Córregos", "SP"));
        cityRep.save(new City(215, "Piracaia", "SP"));
        cityRep.save(new City(216, "Itaí", "SP"));
        cityRep.save(new City(217, "Santa Gertrudes", "SP"));
        cityRep.save(new City(218, "Valparaíso", "SP"));
        cityRep.save(new City(219, "Ilha Solteira", "SP"));
        cityRep.save(new City(220, "Santa Rosa de Viterbo", "SP"));
        cityRep.save(new City(221, "Martinópolis", "SP"));
        cityRep.save(new City(222, "Cajuru", "SP"));
        cityRep.save(new City(223, "Tanabi", "SP"));
        cityRep.save(new City(224, "Bom Jesus dos Perdões", "SP"));
        cityRep.save(new City(225, "Pirajuí", "SP"));
        cityRep.save(new City(226, "Pereira Barreto", "SP"));
        cityRep.save(new City(227, "Angatuba", "SP"));
        cityRep.save(new City(228, "Monte Aprazível", "SP"));
        cityRep.save(new City(229, "Brodowski", "SP"));
        cityRep.save(new City(230, "Potim", "SP"));
        cityRep.save(new City(231, "Álvares Machado", "SP"));
        cityRep.save(new City(232, "Cordeirópolis", "SP"));
        cityRep.save(new City(233, "Igaraçu do Tietê", "SP"));
        cityRep.save(new City(234, "Brotas", "SP"));
        cityRep.save(new City(235, "Iracemápolis", "SP"));
        cityRep.save(new City(236, "Apiaí", "SP"));
        cityRep.save(new City(237, "Santo Antônio de Posse", "SP"));
        cityRep.save(new City(238, "Teodoro Sampaio", "SP"));
        cityRep.save(new City(239, "Taquarituba", "SP"));
        cityRep.save(new City(240, "Tambaú", "SP"));
        cityRep.save(new City(241, "Araçariguama", "SP"));
        cityRep.save(new City(242, "Miguelópolis", "SP"));
        cityRep.save(new City(243, "Palmital", "SP"));
        cityRep.save(new City(244, "Pompeia", "SP"));
        cityRep.save(new City(245, "Lucélia", "SP"));
        cityRep.save(new City(246, "Pradópolis", "SP"));
        cityRep.save(new City(247, "Guapiaçu", "SP"));
        cityRep.save(new City(248, "Nova Granada", "SP"));
        cityRep.save(new City(249, "Cunha", "SP"));
        cityRep.save(new City(250, "Guará", "SP"));
        cityRep.save(new City(251, "Castilho", "SP"));
        cityRep.save(new City(252, "Engenheiro Coelho", "SP"));
        cityRep.save(new City(253, "Capela do Alto", "SP"));
        cityRep.save(new City(254, "Bastos", "SP"));
        cityRep.save(new City(255, "Itatinga", "SP"));
        cityRep.save(new City(256, "Santo Anastácio", "SP"));
        cityRep.save(new City(257, "Junqueirópolis", "SP"));
        cityRep.save(new City(258, "Paranapanema", "SP"));
        cityRep.save(new City(259, "Regente Feijó", "SP"));
        cityRep.save(new City(260, "Cerqueira César", "SP"));
        cityRep.save(new City(261, "Buri", "SP"));
        cityRep.save(new City(262, "Pariquera-Açu", "SP"));
        cityRep.save(new City(263, "Miracatu", "SP"));
        cityRep.save(new City(264, "Pirapora do Bom Jesus", "SP"));
        cityRep.save(new City(265, "Viradouro", "SP"));
        cityRep.save(new City(266, "Caconde", "SP"));
        cityRep.save(new City(267, "Monte Azul Paulista", "SP"));
        cityRep.save(new City(268, "Guareí", "SP"));
        cityRep.save(new City(269, "Águas de Lindoia", "SP"));
        cityRep.save(new City(270, "Alumínio", "SP"));
        cityRep.save(new City(271, "Juquiá", "SP"));
        cityRep.save(new City(272, "Nazaré Paulista", "SP"));
        cityRep.save(new City(273, "Colina", "SP"));
        cityRep.save(new City(274, "Itirapina", "SP"));
        cityRep.save(new City(275, "Cesário Lange", "SP"));
        cityRep.save(new City(276, "Mirante do Paranapanema", "SP"));
        cityRep.save(new City(277, "Paraibuna", "SP"));
        cityRep.save(new City(278, "Conchas", "SP"));
        cityRep.save(new City(279, "Elias Fausto", "SP"));
        cityRep.save(new City(280, "Jacupiranga", "SP"));
        cityRep.save(new City(281, "Cafelândia", "SP"));
        cityRep.save(new City(282, "Bady Bassitt", "SP"));
        cityRep.save(new City(283, "Severínia", "SP"));
        cityRep.save(new City(284, "Itariri", "SP"));
        cityRep.save(new City(285, "Potirendaba", "SP"));
        cityRep.save(new City(286, "Itaberá", "SP"));
        cityRep.save(new City(287, "Charqueada", "SP"));
        cityRep.save(new City(288, "Buritama", "SP"));
        cityRep.save(new City(289, "Salesópolis", "SP"));
        cityRep.save(new City(290, "Pindorama", "SP"));
        cityRep.save(new City(291, "Macatuba", "SP"));
        cityRep.save(new City(292, "Guapiara", "SP"));
        cityRep.save(new City(293, "Pedregulho", "SP"));
        cityRep.save(new City(294, "Tabatinga", "SP"));
        cityRep.save(new City(295, "Ipuã", "SP"));
        cityRep.save(new City(296, "Rosana", "SP"));
        cityRep.save(new City(297, "Ribeirão Branco", "SP"));
        cityRep.save(new City(298, "Altinópolis", "SP"));
        cityRep.save(new City(299, "Borborema", "SP"));
        cityRep.save(new City(300, "Fartura", "SP"));
        cityRep.save(new City(301, "São Lourenço da Serra", "SP"));
        cityRep.save(new City(302, "Panorama", "SP"));
        cityRep.save(new City(303, "Tupi Paulista", "SP"));
        cityRep.save(new City(304, "Santa Adélia", "SP"));
        cityRep.save(new City(305, "Eldorado", "SP"));
        cityRep.save(new City(306, "Pinhalzinho", "SP"));
        cityRep.save(new City(307, "São Simão", "SP"));
        cityRep.save(new City(308, "Itajobi", "SP"));
        cityRep.save(new City(309, "Luiz Antônio", "SP"));
        cityRep.save(new City(310, "Holambra", "SP"));
        cityRep.save(new City(311, "Auriflama", "SP"));
        cityRep.save(new City(312, "Tarumã", "SP"));
        cityRep.save(new City(313, "Itaporanga", "SP"));
        cityRep.save(new City(314, "Ipaussu", "SP"));
        cityRep.save(new City(315, "Boa Esperança do Sul", "SP"));
        cityRep.save(new City(316, "Serra Azul", "SP"));
        cityRep.save(new City(317, "Santa Branca", "SP"));
        cityRep.save(new City(318, "Patrocínio Paulista", "SP"));
        cityRep.save(new City(319, "Flórida Paulista", "SP"));
        cityRep.save(new City(320, "Pacaembu", "SP"));
        cityRep.save(new City(321, "Quatá", "SP"));
        cityRep.save(new City(322, "Itapuí", "SP"));
        cityRep.save(new City(323, "Taguaí", "SP"));
        cityRep.save(new City(324, "Maracaí", "SP"));
        cityRep.save(new City(325, "Urupês", "SP"));
        cityRep.save(new City(326, "Avanhandava", "SP"));
        cityRep.save(new City(327, "Morungaba", "SP"));
        cityRep.save(new City(328, "Piratininga", "SP"));
        cityRep.save(new City(329, "Queluz", "SP"));
        cityRep.save(new City(330, "Piquete", "SP"));
        cityRep.save(new City(331, "Valentim Gentil", "SP"));
        cityRep.save(new City(332, "Palmares Paulista", "SP"));
        cityRep.save(new City(333, "Joanópolis", "SP"));
        cityRep.save(new City(334, "Ribeirão Bonito", "SP"));
        cityRep.save(new City(335, "Palestina", "SP"));
        cityRep.save(new City(336, "Presidente Bernardes", "SP"));
        cityRep.save(new City(337, "Mineiros do Tietê", "SP"));
        cityRep.save(new City(338, "Tapiratiba", "SP"));
        cityRep.save(new City(339, "Sete Barras", "SP"));
        cityRep.save(new City(340, "Riolândia", "SP"));
        cityRep.save(new City(341, "Cananeia", "SP"));
        cityRep.save(new City(342, "Ibirá", "SP"));
        cityRep.save(new City(343, "Tabapuã", "SP"));
        cityRep.save(new City(344, "Bocaina", "SP"));
        cityRep.save(new City(345, "Duartina", "SP"));
        cityRep.save(new City(346, "Chavantes", "SP"));
        cityRep.save(new City(347, "Cardoso", "SP"));
        cityRep.save(new City(348, "Guaiçara", "SP"));
        cityRep.save(new City(349, "Lavínia", "SP"));
        cityRep.save(new City(350, "São Sebastião da Grama", "SP"));
        cityRep.save(new City(351, "Sales Oliveira", "SP"));
        cityRep.save(new City(352, "Bofete", "SP"));
        cityRep.save(new City(353, "Iacanga", "SP"));
        cityRep.save(new City(354, "Nhandeara", "SP"));
        cityRep.save(new City(355, "Pirangi", "SP"));
        cityRep.save(new City(356, "Getulina", "SP"));
        cityRep.save(new City(357, "Pedro de Toledo", "SP"));
        cityRep.save(new City(358, "Estiva Gerbi", "SP"));
        cityRep.save(new City(359, "Ilha Comprida", "SP"));
        cityRep.save(new City(360, "Nova Europa", "SP"));
        cityRep.save(new City(361, "Guaraci", "SP"));
        cityRep.save(new City(362, "Areiópolis", "SP"));
        cityRep.save(new City(363, "Bernardino de Campos", "SP"));
        cityRep.save(new City(364, "Divinolândia", "SP"));
        cityRep.save(new City(365, "Bananal", "SP"));
        cityRep.save(new City(366, "Parapuã", "SP"));
        cityRep.save(new City(367, "São Bento do Sapucaí", "SP"));
        cityRep.save(new City(368, "General Salgado", "SP"));
        cityRep.save(new City(369, "Vera Cruz", "SP"));
        cityRep.save(new City(370, "Rincão", "SP"));
        cityRep.save(new City(371, "Roseira", "SP"));
        cityRep.save(new City(372, "Vargem", "SP"));
        cityRep.save(new City(373, "São Luiz do Paraitinga", "SP"));
        cityRep.save(new City(374, "Cajobi", "SP"));
        cityRep.save(new City(375, "Ouroeste", "SP"));
        cityRep.save(new City(376, "Sarapuí", "SP"));
        cityRep.save(new City(377, "Uchoa", "SP"));
        cityRep.save(new City(378, "Porangaba", "SP"));
        cityRep.save(new City(379, "Torrinha", "SP"));
        cityRep.save(new City(380, "Dumont", "SP"));
        cityRep.save(new City(381, "Rinópolis", "SP"));
        cityRep.save(new City(382, "Manduri", "SP"));
        cityRep.save(new City(383, "Nova Campina", "SP"));
        cityRep.save(new City(384, "Reginópolis", "SP"));
        cityRep.save(new City(385, "Ariranha", "SP"));
        cityRep.save(new City(386, "Herculândia", "SP"));
        cityRep.save(new City(387, "Igaratá", "SP"));
        cityRep.save(new City(388, "Iaras", "SP"));
        cityRep.save(new City(389, "Terra Roxa", "SP"));
        cityRep.save(new City(390, "Salto Grande", "SP"));
        cityRep.save(new City(391, "Cedral", "SP"));
        cityRep.save(new City(392, "Euclides da Cunha Paulista", "SP"));
        cityRep.save(new City(393, "Palmeira d'Oeste", "SP"));
        cityRep.save(new City(394, "Bálsamo", "SP"));
        cityRep.save(new City(395, "Urânia", "SP"));
        cityRep.save(new City(396, "Rafard", "SP"));
        cityRep.save(new City(397, "Dobrada", "SP"));
        cityRep.save(new City(398, "Vista Alegre do Alto", "SP"));
        cityRep.save(new City(399, "São José da Bela Vista", "SP"));
        cityRep.save(new City(400, "Paulo de Faria", "SP"));
        cityRep.save(new City(401, "Neves Paulista", "SP"));
        cityRep.save(new City(402, "Dourado", "SP"));
        cityRep.save(new City(403, "Santa Lúcia", "SP"));
        cityRep.save(new City(404, "Pereiras", "SP"));
        cityRep.save(new City(405, "Clementina", "SP"));
        cityRep.save(new City(406, "Cristais Paulista", "SP"));
        cityRep.save(new City(407, "Ouro Verde", "SP"));
        cityRep.save(new City(408, "Arealva", "SP"));
        cityRep.save(new City(409, "Santo Antônio do Aracanguá", "SP"));
        cityRep.save(new City(410, "Estrela d'Oeste", "SP"));
        cityRep.save(new City(411, "Saltinho", "SP"));
        cityRep.save(new City(412, "Irapuru", "SP"));
        cityRep.save(new City(413, "Icém", "SP"));
        cityRep.save(new City(414, "Guaraçaí", "SP"));
        cityRep.save(new City(415, "Águas da Prata", "SP"));
        cityRep.save(new City(416, "Iepê", "SP"));
        cityRep.save(new City(417, "Macaubal", "SP"));
        cityRep.save(new City(418, "Bilac", "SP"));
        cityRep.save(new City(419, "Monte Alegre do Sul", "SP"));
        cityRep.save(new City(420, "Lindoia", "SP"));
        cityRep.save(new City(421, "Irapuã", "SP"));
        cityRep.save(new City(422, "Catiguá", "SP"));
        cityRep.save(new City(423, "Itobi", "SP"));
        cityRep.save(new City(424, "Ibirarema", "SP"));
        cityRep.save(new City(425, "Tapiraí", "SP"));
        cityRep.save(new City(426, "Sud Mennucci", "SP"));
        cityRep.save(new City(427, "Guatapará", "SP"));
        cityRep.save(new City(428, "São Pedro do Turvo", "SP"));
        cityRep.save(new City(429, "Ipeúna", "SP"));
        cityRep.save(new City(430, "Restinga", "SP"));
        cityRep.save(new City(431, "Ribeirão Grande", "SP"));
        cityRep.save(new City(432, "Barra do Turvo", "SP"));
        cityRep.save(new City(433, "Tarabai", "SP"));
        cityRep.save(new City(434, "Nuporanga", "SP"));
        cityRep.save(new City(435, "Barbosa", "SP"));
        cityRep.save(new City(436, "Pauliceia", "SP"));
        cityRep.save(new City(437, "Lavrinhas", "SP"));
        cityRep.save(new City(438, "Cosmorama", "SP"));
        cityRep.save(new City(439, "Jaci", "SP"));
        cityRep.save(new City(440, "Orindiúva", "SP"));
        cityRep.save(new City(441, "Nova Aliança", "SP"));
        cityRep.save(new City(442, "Santo Antônio da Alegria", "SP"));
        cityRep.save(new City(443, "Tuiuti", "SP"));
        cityRep.save(new City(444, "Jaborandi", "SP"));
        cityRep.save(new City(445, "Santo Antônio do Pinhal", "SP"));
        cityRep.save(new City(446, "Anhembi", "SP"));
        cityRep.save(new City(447, "Jambeiro", "SP"));
        cityRep.save(new City(448, "Quintana", "SP"));
        cityRep.save(new City(449, "Guarantã", "SP"));
        cityRep.save(new City(450, "Natividade da Serra", "SP"));
        cityRep.save(new City(451, "Itirapuã", "SP"));
        cityRep.save(new City(452, "Oriente", "SP"));
        cityRep.save(new City(453, "Pardinho", "SP"));
        cityRep.save(new City(454, "Paraíso", "SP"));
        cityRep.save(new City(455, "Gália", "SP"));
        cityRep.save(new City(456, "Sales", "SP"));
        cityRep.save(new City(457, "Ubarana", "SP"));
        cityRep.save(new City(458, "Arandu", "SP"));
        cityRep.save(new City(459, "Silveiras", "SP"));
        cityRep.save(new City(460, "Taciba", "SP"));
        cityRep.save(new City(461, "Taiaçu", "SP"));
        cityRep.save(new City(462, "Iacri", "SP"));
        cityRep.save(new City(463, "Santa Maria da Serra", "SP"));
        cityRep.save(new City(464, "Colômbia", "SP"));
        cityRep.save(new City(465, "Alambari", "SP"));
        cityRep.save(new City(466, "Coroados", "SP"));
        cityRep.save(new City(467, "Poloni", "SP"));
        cityRep.save(new City(468, "Pedra Bela", "SP"));
        cityRep.save(new City(469, "Águas de Santa Bárbara", "SP"));
        cityRep.save(new City(470, "Echaporã", "SP"));
        cityRep.save(new City(471, "Campina do Monte Alegre", "SP"));
        cityRep.save(new City(472, "Piacatu", "SP"));
        cityRep.save(new City(473, "Santa Albertina", "SP"));
        cityRep.save(new City(474, "Américo de Campos", "SP"));
        cityRep.save(new City(475, "Marabá Paulista", "SP"));
        cityRep.save(new City(476, "Caiuá", "SP"));
        cityRep.save(new City(477, "Novais", "SP"));
        cityRep.save(new City(478, "Santo Antônio do Jardim", "SP"));
        cityRep.save(new City(479, "Balbinos", "SP"));
        cityRep.save(new City(480, "Taquarivaí", "SP"));
        cityRep.save(new City(481, "Luiziânia", "SP"));
        cityRep.save(new City(482, "Três Fronteiras", "SP"));
        cityRep.save(new City(483, "Fernando Prestes", "SP"));
        cityRep.save(new City(484, "Guaimbê", "SP"));
        cityRep.save(new City(485, "Barra do Chapéu", "SP"));
        cityRep.save(new City(486, "Braúna", "SP"));
        cityRep.save(new City(487, "Aramina", "SP"));
        cityRep.save(new City(488, "Sabino", "SP"));
        cityRep.save(new City(489, "Santa Ernestina", "SP"));
        cityRep.save(new City(490, "Mendonça", "SP"));
        cityRep.save(new City(491, "Taiúva", "SP"));
        cityRep.save(new City(492, "Ipiguá", "SP"));
        cityRep.save(new City(493, "Riversul", "SP"));
        cityRep.save(new City(494, "Avaí", "SP"));
        cityRep.save(new City(495, "Salmourão", "SP"));
        cityRep.save(new City(496, "Pratânia", "SP"));
        cityRep.save(new City(497, "Guzolândia", "SP"));
        cityRep.save(new City(498, "Planalto", "SP"));
        cityRep.save(new City(499, "Nipoã", "SP"));
        cityRep.save(new City(500, "Canitar", "SP"));
        cityRep.save(new City(501, "Álvaro de Carvalho", "SP"));
        cityRep.save(new City(502, "Canas", "SP"));
        cityRep.save(new City(503, "Analândia", "SP"));
        cityRep.save(new City(504, "Campos Novos Paulista", "SP"));
        cityRep.save(new City(505, "Itapura", "SP"));
        cityRep.save(new City(506, "Mirassolândia", "SP"));
        cityRep.save(new City(507, "Narandiba", "SP"));
        cityRep.save(new City(508, "Lagoinha", "SP"));
        cityRep.save(new City(509, "Indiana", "SP"));
        cityRep.save(new City(510, "Espírito Santo do Turvo", "SP"));
        cityRep.save(new City(511, "Boraceia", "SP"));
        cityRep.save(new City(512, "Gastão Vidigal", "SP"));
        cityRep.save(new City(513, "Glicério", "SP"));
        cityRep.save(new City(514, "Santópolis do Aguapeí", "SP"));
        cityRep.save(new City(515, "Gavião Peixoto", "SP"));
        cityRep.save(new City(516, "Ubirajara", "SP"));
        cityRep.save(new City(517, "Júlio Mesquita", "SP"));
        cityRep.save(new City(518, "Motuca", "SP"));
        cityRep.save(new City(519, "Ribeirão Corrente", "SP"));
        cityRep.save(new City(520, "Monteiro Lobato", "SP"));
        cityRep.save(new City(521, "Pontalinda", "SP"));
        cityRep.save(new City(522, "Coronel Macedo", "SP"));
        cityRep.save(new City(523, "Lupércio", "SP"));
        cityRep.save(new City(524, "João Ramalho", "SP"));
        cityRep.save(new City(525, "Santa Cruz da Conceição", "SP"));
        cityRep.save(new City(526, "Ribeirão do Sul", "SP"));
        cityRep.save(new City(527, "Buritizal", "SP"));
        cityRep.save(new City(528, "Murutinga do Sul", "SP"));
        cityRep.save(new City(529, "Tejupá", "SP"));
        cityRep.save(new City(530, "Onda Verde", "SP"));
        cityRep.save(new City(531, "Sandovalina", "SP"));
        cityRep.save(new City(532, "Ocauçu", "SP"));
        cityRep.save(new City(533, "Itapirapuã Paulista", "SP"));
        cityRep.save(new City(534, "Cabrália Paulista", "SP"));
        cityRep.save(new City(535, "Pracinha", "SP"));
        cityRep.save(new City(536, "Iporanga", "SP"));
        cityRep.save(new City(537, "Caiabu", "SP"));
        cityRep.save(new City(538, "Altair", "SP"));
        cityRep.save(new City(539, "Alfredo Marcondes", "SP"));
        cityRep.save(new City(540, "Monte Castelo", "SP"));
        cityRep.save(new City(541, "Nova Luzitânia", "SP"));
        cityRep.save(new City(542, "Aparecida d'Oeste", "SP"));
        cityRep.save(new City(543, "Populina", "SP"));
        cityRep.save(new City(544, "Anhumas", "SP"));
        cityRep.save(new City(545, "São José do Barreiro", "SP"));
        cityRep.save(new City(546, "Paranapuã", "SP"));
        cityRep.save(new City(547, "Mariápolis", "SP"));
        cityRep.save(new City(548, "Alto Alegre", "SP"));
        cityRep.save(new City(549, "Presidente Alves", "SP"));
        cityRep.save(new City(550, "Corumbataí", "SP"));
        cityRep.save(new City(551, "Nova Independência", "SP"));
        cityRep.save(new City(552, "Inúbia Paulista", "SP"));
        cityRep.save(new City(553, "Suzanápolis", "SP"));
        cityRep.save(new City(554, "Bom Sucesso de Itararé", "SP"));
        cityRep.save(new City(555, "Areias", "SP"));
        cityRep.save(new City(556, "Itaju", "SP"));
        cityRep.save(new City(557, "Indiaporã", "SP"));
        cityRep.save(new City(558, "Quadra", "SP"));
        cityRep.save(new City(559, "Redenção da Serra", "SP"));
        cityRep.save(new City(560, "Meridiano", "SP"));
        cityRep.save(new City(561, "Piquerobi", "SP"));
        cityRep.save(new City(562, "Elisiário", "SP"));
        cityRep.save(new City(563, "Macedônia", "SP"));
        cityRep.save(new City(564, "Álvares Florence", "SP"));
        cityRep.save(new City(565, "Rifaina", "SP"));
        cityRep.save(new City(566, "Sarutaiá", "SP"));
        cityRep.save(new City(567, "Platina", "SP"));
        cityRep.save(new City(568, "Adolfo", "SP"));
        cityRep.save(new City(569, "Sebastianópolis do Sul", "SP"));
        cityRep.save(new City(570, "Águas de São Pedro", "SP"));
        cityRep.save(new City(571, "Mombuca", "SP"));
        cityRep.save(new City(572, "Barão de Antonina", "SP"));
        cityRep.save(new City(573, "Queiroz", "SP"));
        cityRep.save(new City(574, "Jumirim", "SP"));
        cityRep.save(new City(575, "Pongaí", "SP"));
        cityRep.save(new City(576, "Itaoca", "SP"));
        cityRep.save(new City(577, "Ribeira", "SP"));
        cityRep.save(new City(578, "Alvinlândia", "SP"));
        cityRep.save(new City(579, "Emilianópolis", "SP"));
        cityRep.save(new City(580, "Nantes", "SP"));
        cityRep.save(new City(581, "Rubineia", "SP"));
        cityRep.save(new City(582, "Rubiácea", "SP"));
        cityRep.save(new City(583, "Jeriquara", "SP"));
        cityRep.save(new City(584, "Santo Expedito", "SP"));
        cityRep.save(new City(585, "Mira Estrela", "SP"));
        cityRep.save(new City(586, "Magda", "SP"));
        cityRep.save(new City(587, "Pedrinhas Paulista", "SP"));
        cityRep.save(new City(588, "Marapoama", "SP"));
        cityRep.save(new City(589, "Bento de Abreu", "SP"));
        cityRep.save(new City(590, "Santa Mercedes", "SP"));
        cityRep.save(new City(591, "Floreal", "SP"));
        cityRep.save(new City(592, "Brejo Alegre", "SP"));
        cityRep.save(new City(593, "São Francisco", "SP"));
        cityRep.save(new City(594, "Taquaral", "SP"));
        cityRep.save(new City(595, "Cândido Rodrigues", "SP"));
        cityRep.save(new City(596, "Gabriel Monteiro", "SP"));
        cityRep.save(new City(597, "Estrela do Norte", "SP"));
        cityRep.save(new City(598, "Zacarias", "SP"));
        cityRep.save(new City(599, "Borebi", "SP"));
        cityRep.save(new City(600, "Florínea", "SP"));
        cityRep.save(new City(601, "Timburi", "SP"));
        cityRep.save(new City(602, "Lutécia", "SP"));
        cityRep.save(new City(603, "Oscar Bressane", "SP"));
        cityRep.save(new City(604, "Pontes Gestal", "SP"));
        cityRep.save(new City(605, "São João das Duas Pontes", "SP"));
        cityRep.save(new City(606, "Cássia dos Coqueiros", "SP"));
        cityRep.save(new City(607, "Santa Rita d'Oeste", "SP"));
        cityRep.save(new City(608, "Pedranópolis", "SP"));
        cityRep.save(new City(609, "Óleo", "SP"));
        cityRep.save(new City(610, "Arapeí", "SP"));
        cityRep.save(new City(611, "Embaúba", "SP"));
        cityRep.save(new City(612, "Sagres", "SP"));
        cityRep.save(new City(613, "Torre de Pedra", "SP"));
        cityRep.save(new City(614, "Lucianópolis", "SP"));
        cityRep.save(new City(615, "Nova Guataporanga", "SP"));
        cityRep.save(new City(616, "Lourdes", "SP"));
        cityRep.save(new City(617, "Monções", "SP"));
        cityRep.save(new City(618, "Ribeirão dos Índios", "SP"));
        cityRep.save(new City(619, "Parisi", "SP"));
        cityRep.save(new City(620, "Santa Cruz da Esperança", "SP"));
        cityRep.save(new City(621, "Santa Clara d'Oeste", "SP"));
        cityRep.save(new City(622, "Dolcinópolis", "SP"));
        cityRep.save(new City(623, "Marinópolis", "SP"));
        cityRep.save(new City(624, "São João do Pau d'Alho", "SP"));
        cityRep.save(new City(625, "Cruzália", "SP"));
        cityRep.save(new City(626, "Turiúba", "SP"));
        cityRep.save(new City(627, "Guarani d'Oeste", "SP"));
        cityRep.save(new City(628, "São João de Iracema", "SP"));
        cityRep.save(new City(629, "Mesópolis", "SP"));
        cityRep.save(new City(630, "União Paulista", "SP"));
        cityRep.save(new City(631, "Nova Canaã Paulista", "SP"));
        cityRep.save(new City(632, "Vitória Brasil", "SP"));
        cityRep.save(new City(633, "Paulistânia", "SP"));
        cityRep.save(new City(634, "Aspásia", "SP"));
        cityRep.save(new City(635, "Dirce Reis", "SP"));
        cityRep.save(new City(636, "Arco-Íris", "SP"));
        cityRep.save(new City(637, "Trabiju", "SP"));
        cityRep.save(new City(638, "Fernão", "SP"));
        cityRep.save(new City(639, "Turmalina", "SP"));
        cityRep.save(new City(640, "Santa Salete", "SP"));
        cityRep.save(new City(641, "Santana da Ponte Pensa", "SP"));
        cityRep.save(new City(642, "Flora Rica", "SP"));
        cityRep.save(new City(643, "Nova Castilho", "SP"));
        cityRep.save(new City(644, "Uru", "SP"));
        cityRep.save(new City(645, "Borá", "SP"));

        cityRep.save(new City(646, "Abdon Batista", "SC"));
        cityRep.save(new City(647, "Abelardo Luz", "SC"));
        cityRep.save(new City(648, "Agrolândia", "SC"));
        cityRep.save(new City(649, "Agronômica", "SC"));
        cityRep.save(new City(650, "Água Doce", "SC"));
        cityRep.save(new City(651, "Águas Frias", "SC"));
        cityRep.save(new City(652, "Águas Mornas", "SC"));
        cityRep.save(new City(653, "Águas de Chapecó", "SC"));
        cityRep.save(new City(654, "Alfredo Wagner", "SC"));
        cityRep.save(new City(655, "Alto Bela Vista", "SC"));
        cityRep.save(new City(656, "Anchieta", "SC"));
        cityRep.save(new City(657, "Angelina", "SC"));
        cityRep.save(new City(658, "Anita Garibaldi", "SC"));
        cityRep.save(new City(659, "Anitápolis", "SC"));
        cityRep.save(new City(660, "Antônio Carlos", "SC"));
        cityRep.save(new City(661, "Apiúna", "SC"));
        cityRep.save(new City(662, "Arabutã", "SC"));
        cityRep.save(new City(663, "Araquari", "SC"));
        cityRep.save(new City(664, "Araranguá", "SC"));
        cityRep.save(new City(665, "Armazém", "SC"));
        cityRep.save(new City(666, "Arroio Trinta", "SC"));
        cityRep.save(new City(667, "Arvoredo", "SC"));
        cityRep.save(new City(668, "Ascurra", "SC"));
        cityRep.save(new City(669, "Atalanta", "SC"));
        cityRep.save(new City(670, "Aurora", "SC"));
        cityRep.save(new City(671, "Balneário Arroio do Silva", "SC"));
        cityRep.save(new City(672, "Balneário Barra do Sul", "SC"));
        cityRep.save(new City(673, "Balneário Camboriú", "SC"));
        cityRep.save(new City(674, "Balneário Gaivota", "SC"));
        cityRep.save(new City(675, "Balneário Piçarras", "SC"));
        cityRep.save(new City(676, "Balneário Rincão", "SC"));
        cityRep.save(new City(677, "Bandeirante", "SC"));
        cityRep.save(new City(678, "Barra Bonita", "SC"));
        cityRep.save(new City(679, "Barra Velha", "SC"));
        cityRep.save(new City(680, "Bela Vista do Toldo", "SC"));
        cityRep.save(new City(681, "Belmonte", "SC"));
        cityRep.save(new City(682, "Benedito Novo", "SC"));
        cityRep.save(new City(683, "Biguaçu", "SC"));
        cityRep.save(new City(684, "Blumenau", "SC"));
        cityRep.save(new City(685, "Bocaina do Sul", "SC"));
        cityRep.save(new City(686, "Bom Jardim da Serra", "SC"));
        cityRep.save(new City(687, "Bom Jesus", "SC"));
        cityRep.save(new City(688, "Bom Jesus do Oeste", "SC"));
        cityRep.save(new City(689, "Bom Retiro", "SC"));
        cityRep.save(new City(690, "Bombinhas", "SC"));
        cityRep.save(new City(691, "Botuverá", "SC"));
        cityRep.save(new City(692, "Braço do Norte", "SC"));
        cityRep.save(new City(693, "Braço do Trombudo", "SC"));
        cityRep.save(new City(694, "Brunópolis", "SC"));
        cityRep.save(new City(695, "Brusque", "SC"));
        cityRep.save(new City(696, "Caçador", "SC"));
        cityRep.save(new City(697, "Caibi", "SC"));
        cityRep.save(new City(698, "Calmon", "SC"));
        cityRep.save(new City(699, "Camboriú", "SC"));
        cityRep.save(new City(700, "Campo Alegre", "SC"));
        cityRep.save(new City(701, "Campo Belo do Sul", "SC"));
        cityRep.save(new City(702, "Campo Erê", "SC"));
        cityRep.save(new City(703, "Campos Novos", "SC"));
        cityRep.save(new City(704, "Canelinha", "SC"));
        cityRep.save(new City(705, "Canoinhas", "SC"));
        cityRep.save(new City(706, "Capinzal", "SC"));
        cityRep.save(new City(707, "Capivari de Baixo", "SC"));
        cityRep.save(new City(708, "Capão Alto", "SC"));
        cityRep.save(new City(709, "Catanduvas", "SC"));
        cityRep.save(new City(710, "Caxambu do Sul", "SC"));
        cityRep.save(new City(711, "Celso Ramos", "SC"));
        cityRep.save(new City(712, "Cerro Negro", "SC"));
        cityRep.save(new City(713, "Chapadão do Lageado", "SC"));
        cityRep.save(new City(714, "Chapecó", "SC"));
        cityRep.save(new City(715, "Cocal do Sul", "SC"));
        cityRep.save(new City(716, "Concórdia", "SC"));
        cityRep.save(new City(717, "Cordilheira Alta", "SC"));
        cityRep.save(new City(718, "Coronel Freitas", "SC"));
        cityRep.save(new City(719, "Coronel Martins", "SC"));
        cityRep.save(new City(720, "Correia Pinto", "SC"));
        cityRep.save(new City(721, "Corupá", "SC"));
        cityRep.save(new City(722, "Criciúma", "SC"));
        cityRep.save(new City(726, "Cunha Porã", "SC"));
        cityRep.save(new City(727, "Cunhataí", "SC"));
        cityRep.save(new City(728, "Curitibanos", "SC"));
        cityRep.save(new City(729, "Descanso", "SC"));
        cityRep.save(new City(730, "Dionísio Cerqueira", "SC"));
        cityRep.save(new City(731, "Dona Emma", "SC"));
        cityRep.save(new City(732, "Doutor Pedrinho", "SC"));
        cityRep.save(new City(733, "Entre Rios", "SC"));
        cityRep.save(new City(734, "Ermo", "SC"));
        cityRep.save(new City(735, "Erval Velho", "SC"));
        cityRep.save(new City(736, "Faxinal dos Guedes", "SC"));
        cityRep.save(new City(737, "Flor do Sertão", "SC"));
        cityRep.save(new City(738, "Florianópolis", "SC"));
        cityRep.save(new City(739, "Formosa do Sul", "SC"));
        cityRep.save(new City(740, "Forquilhinha", "SC"));
        cityRep.save(new City(741, "Fraiburgo", "SC"));
        cityRep.save(new City(742, "Frei Rogério", "SC"));
        cityRep.save(new City(743, "Galvão", "SC"));
        cityRep.save(new City(744, "Garopaba", "SC"));
        cityRep.save(new City(745, "Garuva", "SC"));
        cityRep.save(new City(746, "Gaspar", "SC"));
        cityRep.save(new City(747, "Governador Celso Ramos", "SC"));
        cityRep.save(new City(748, "Grão-Pará", "SC"));
        cityRep.save(new City(749, "Gravatal", "SC"));
        cityRep.save(new City(750, "Guabiruba", "SC"));
        cityRep.save(new City(751, "Guaraciaba", "SC"));
        cityRep.save(new City(752, "Guaramirim", "SC"));
        cityRep.save(new City(753, "Guarujá do Sul", "SC"));
        cityRep.save(new City(754, "Guatambu", "SC"));
        cityRep.save(new City(755, "Herval d'Oeste", "SC"));
        cityRep.save(new City(756, "Ibiam", "SC"));
        cityRep.save(new City(757, "Ibicaré", "SC"));
        cityRep.save(new City(758, "Ibirama", "SC"));
        cityRep.save(new City(759, "Içara", "SC"));
        cityRep.save(new City(760, "Ilhota", "SC"));
        cityRep.save(new City(761, "Imaruí", "SC"));
        cityRep.save(new City(762, "Imbituba", "SC"));
        cityRep.save(new City(763, "Imbuia", "SC"));
        cityRep.save(new City(764, "Indaial", "SC"));
        cityRep.save(new City(765, "Iomerê", "SC"));
        cityRep.save(new City(766, "Ipira", "SC"));
        cityRep.save(new City(767, "Iporã do Oeste", "SC"));
        cityRep.save(new City(768, "Ipuaçu", "SC"));
        cityRep.save(new City(769, "Ipumirim", "SC"));
        cityRep.save(new City(770, "Iraceminha", "SC"));
        cityRep.save(new City(771, "Irani", "SC"));
        cityRep.save(new City(772, "Irati", "SC"));
        cityRep.save(new City(773, "Irineópolis", "SC"));
        cityRep.save(new City(774, "Itá", "SC"));
        cityRep.save(new City(775, "Itaiópolis", "SC"));
        cityRep.save(new City(776, "Itajaí", "SC"));
        cityRep.save(new City(777, "Itapema", "SC"));
        cityRep.save(new City(778, "Itapiranga", "SC"));
        cityRep.save(new City(779, "Itapoá", "SC"));
        cityRep.save(new City(780, "Ituporanga", "SC"));
        cityRep.save(new City(781, "Jaborá", "SC"));
        cityRep.save(new City(782, "Jacinto Machado", "SC"));
        cityRep.save(new City(783, "Jaguaruna", "SC"));
        cityRep.save(new City(784, "Jaraguá do Sul", "SC"));
        cityRep.save(new City(785, "Jardinópolis", "SC"));
        cityRep.save(new City(786, "Joaçaba", "SC"));
        cityRep.save(new City(787, "Joinville", "SC"));
        cityRep.save(new City(788, "José Boiteux", "SC"));
        cityRep.save(new City(789, "Jupiá", "SC"));
        cityRep.save(new City(790, "Lacerdópolis", "SC"));
        cityRep.save(new City(791, "Lages", "SC"));
        cityRep.save(new City(792, "Laguna", "SC"));
        cityRep.save(new City(793, "Lajeado Grande", "SC"));
        cityRep.save(new City(794, "Laurentino", "SC"));
        cityRep.save(new City(795, "Lauro Müller", "SC"));
        cityRep.save(new City(796, "Lebon Régis", "SC"));
        cityRep.save(new City(797, "Leoberto Leal", "SC"));
        cityRep.save(new City(798, "Lindóia do Sul", "SC"));
        cityRep.save(new City(799, "Lontras", "SC"));
        cityRep.save(new City(800, "Luiz Alves", "SC"));
        cityRep.save(new City(801, "Luzerna", "SC"));
        cityRep.save(new City(802, "Macieira", "SC"));
        cityRep.save(new City(803, "Mafra", "SC"));
        cityRep.save(new City(804, "Major Gercino", "SC"));
        cityRep.save(new City(805, "Major Vieira", "SC"));
        cityRep.save(new City(806, "Maracajá", "SC"));
        cityRep.save(new City(807, "Maravilha", "SC"));
        cityRep.save(new City(808, "Marema", "SC"));
        cityRep.save(new City(809, "Massaranduba", "SC"));
        cityRep.save(new City(810, "Matos Costa", "SC"));
        cityRep.save(new City(811, "Meleiro", "SC"));
        cityRep.save(new City(812, "Mirim Doce", "SC"));
        cityRep.save(new City(813, "Modelo", "SC"));
        cityRep.save(new City(814, "Mondaí", "SC"));
        cityRep.save(new City(815, "Monte Carlo", "SC"));
        cityRep.save(new City(816, "Monte Castelo", "SC"));
        cityRep.save(new City(817, "Morro da Fumaça", "SC"));
        cityRep.save(new City(818, "Morro Grande", "SC"));
        cityRep.save(new City(819, "Navegantes", "SC"));
        cityRep.save(new City(820, "Nova Erechim", "SC"));
        cityRep.save(new City(821, "Nova Itaberaba", "SC"));
        cityRep.save(new City(822, "Nova Trento", "SC"));
        cityRep.save(new City(823, "Nova Veneza", "SC"));
        cityRep.save(new City(824, "Novo Horizonte", "SC"));
        cityRep.save(new City(825, "Orleans", "SC"));
        cityRep.save(new City(826, "Otacílio Costa", "SC"));
        cityRep.save(new City(827, "Ouro", "SC"));
        cityRep.save(new City(828, "Ouro Verde", "SC"));
        cityRep.save(new City(829, "Paial", "SC"));
        cityRep.save(new City(830, "Painel", "SC"));
        cityRep.save(new City(831, "Palhoça", "SC"));
        cityRep.save(new City(832, "Palma Sola", "SC"));
        cityRep.save(new City(833, "Palmeira", "SC"));
        cityRep.save(new City(834, "Palmitos", "SC"));
        cityRep.save(new City(835, "Papanduva", "SC"));
        cityRep.save(new City(836, "Paraíso", "SC"));
        cityRep.save(new City(837, "Passo de Torres", "SC"));
        cityRep.save(new City(838, "Passos Maia", "SC"));
        cityRep.save(new City(839, "Paulo Lopes", "SC"));
        cityRep.save(new City(840, "Pedras Grandes", "SC"));
        cityRep.save(new City(841, "Penha", "SC"));
        cityRep.save(new City(842, "Peritiba", "SC"));
        cityRep.save(new City(843, "Pescaria Brava", "SC"));
        cityRep.save(new City(844, "Petrolândia", "SC"));
        cityRep.save(new City(845, "Pinhalzinho", "SC"));
        cityRep.save(new City(846, "Pinheiro Preto", "SC"));
        cityRep.save(new City(847, "Piratuba", "SC"));
        cityRep.save(new City(848, "Planalto Alegre", "SC"));
        cityRep.save(new City(849, "Pomerode", "SC"));
        cityRep.save(new City(850, "Ponte Alta do Norte", "SC"));
        cityRep.save(new City(851, "Ponte Alta", "SC"));
        cityRep.save(new City(852, "Ponte Serrada", "SC"));
        cityRep.save(new City(853, "Porto Belo", "SC"));
        cityRep.save(new City(854, "Porto União", "SC"));
        cityRep.save(new City(855, "Pouso Redondo", "SC"));
        cityRep.save(new City(856, "Praia Grande", "SC"));
        cityRep.save(new City(857, "Presidente Castello Branco", "SC"));
        cityRep.save(new City(858, "Presidente Getúlio", "SC"));
        cityRep.save(new City(859, "Presidente Nereu", "SC"));
        cityRep.save(new City(860, "Princesa", "SC"));
        cityRep.save(new City(861, "Quilombo", "SC"));
        cityRep.save(new City(862, "Rancho Queimado", "SC"));
        cityRep.save(new City(863, "Rio das Antas", "SC"));
        cityRep.save(new City(864, "Rio do Campo", "SC"));
        cityRep.save(new City(865, "Rio do Oeste", "SC"));
        cityRep.save(new City(866, "Rio do Sul", "SC"));
        cityRep.save(new City(867, "Rio dos Cedros", "SC"));
        cityRep.save(new City(868, "Rio Fortuna", "SC"));
        cityRep.save(new City(869, "Rio Negrinho", "SC"));
        cityRep.save(new City(870, "Rio Rufino", "SC"));
        cityRep.save(new City(871, "Riqueza", "SC"));
        cityRep.save(new City(872, "Rodeio", "SC"));
        cityRep.save(new City(873, "Romelândia", "SC"));
        cityRep.save(new City(874, "Salete", "SC"));
        cityRep.save(new City(875, "Saltinho", "SC"));
        cityRep.save(new City(876, "Salto Veloso", "SC"));
        cityRep.save(new City(877, "Sangão", "SC"));
        cityRep.save(new City(878, "Santa Cecília", "SC"));
        cityRep.save(new City(879, "Santa Helena", "SC"));
        cityRep.save(new City(880, "Santa Rosa de Lima", "SC"));
        cityRep.save(new City(881, "Santa Rosa do Sul", "SC"));
        cityRep.save(new City(882, "Santa Terezinha", "SC"));
        cityRep.save(new City(883, "Santa Terezinha do Progresso", "SC"));
        cityRep.save(new City(884, "Santiago do Sul", "SC"));
        cityRep.save(new City(885, "Santo Amaro da Imperatriz", "SC"));
        cityRep.save(new City(886, "São Bento do Sul", "SC"));
        cityRep.save(new City(887, "São Bernardino", "SC"));
        cityRep.save(new City(888, "São Bonifácio", "SC"));
        cityRep.save(new City(889, "São Carlos", "SC"));
        cityRep.save(new City(890, "São Cristóvão do Sul", "SC"));
        cityRep.save(new City(891, "São Domingos", "SC"));
        cityRep.save(new City(892, "São Francisco do Sul", "SC"));
        cityRep.save(new City(893, "São João Batista", "SC"));
        cityRep.save(new City(894, "São João do Itaperiú", "SC"));
        cityRep.save(new City(895, "São João do Oeste", "SC"));
        cityRep.save(new City(896, "São João do Sul", "SC"));
        cityRep.save(new City(897, "São Joaquim", "SC"));
        cityRep.save(new City(898, "São José", "SC"));
        cityRep.save(new City(899, "São José do Cedro", "SC"));
        cityRep.save(new City(900, "São José do Cerrito", "SC"));
        cityRep.save(new City(901, "São Lourenço do Oeste", "SC"));
        cityRep.save(new City(902, "São Ludgero", "SC"));
        cityRep.save(new City(903, "São Martinho", "SC"));
        cityRep.save(new City(904, "São Miguel da Boa Vista", "SC"));
        cityRep.save(new City(905, "São Miguel do Oeste", "SC"));
        cityRep.save(new City(906, "São Pedro de Alcântara", "SC"));
        cityRep.save(new City(907, "Saudades", "SC"));
        cityRep.save(new City(908, "Schroeder", "SC"));
        cityRep.save(new City(909, "Seara", "SC"));
        cityRep.save(new City(910, "Serra Alta", "SC"));
        cityRep.save(new City(911, "Siderópolis", "SC"));
        cityRep.save(new City(912, "Sombrio", "SC"));
        cityRep.save(new City(913, "Sul Brasil", "SC"));
        cityRep.save(new City(914, "Taió", "SC"));
        cityRep.save(new City(915, "Tangará", "SC"));
        cityRep.save(new City(916, "Tigrinhos", "SC"));
        cityRep.save(new City(917, "Tijucas", "SC"));
        cityRep.save(new City(918, "Timbé do Sul", "SC"));
        cityRep.save(new City(919, "Timbó", "SC"));
        cityRep.save(new City(920, "Timbó Grande", "SC"));
        cityRep.save(new City(921, "Três Barras", "SC"));
        cityRep.save(new City(922, "Treviso", "SC"));
        cityRep.save(new City(923, "Treze de Maio", "SC"));
        cityRep.save(new City(924, "Treze Tílias", "SC"));
        cityRep.save(new City(925, "Trombudo Central", "SC"));
        cityRep.save(new City(926, "Tubarão", "SC"));
        cityRep.save(new City(927, "Tunápolis", "SC"));
        cityRep.save(new City(928, "Turvo", "SC"));
        cityRep.save(new City(929, "União do Oeste", "SC"));
        cityRep.save(new City(930, "Urubici", "SC"));
        cityRep.save(new City(931, "Urupema", "SC"));
        cityRep.save(new City(932, "Urussanga", "SC"));
        cityRep.save(new City(933, "Vargeão", "SC"));
        cityRep.save(new City(934, "Vargem", "SC"));
        cityRep.save(new City(935, "Vargem Bonita", "SC"));
        cityRep.save(new City(936, "Vidal Ramos", "SC"));
        cityRep.save(new City(937, "Videira", "SC"));
        cityRep.save(new City(938, "Vitor Meireles", "SC"));
        cityRep.save(new City(939, "Witmarsum", "SC"));
        cityRep.save(new City(940, "Xanxerê", "SC"));
        cityRep.save(new City(941, "Xavantina", "SC"));
        cityRep.save(new City(942, "Xaxim", "SC"));
        cityRep.save(new City(943, "Zortéa", "SC"));

        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        City city = new City();
        city.setId(33);

        clientRep.save(new Client(1,"Kevin Benjamin Francisco Corte Real", 0, (Date)formatter.parse("15/9/1999"), 21, city));
        clientRep.save(new Client(2,"Maya Heloisa Beatriz Assunção", 1, (Date)formatter.parse("24/6/1999"), 21, city));
        clientRep.save(new Client(3,"Renato Vitor Lopes", 0, (Date)formatter.parse("27/2/1999"), 21, city));
        city.setId(100);
        clientRep.save(new Client(4,"Lucas Igor Anthony Fernandes", 0, (Date)formatter.parse("3/4/1999"), 21, city));
        clientRep.save(new Client(5,"Elias Nelson Cardoso", 0, (Date)formatter.parse("15/9/1999"), 21, city));
        clientRep.save(new Client(6,"Kaique Victor Heitor Ribeiro", 0, (Date)formatter.parse("11/10/1999"), 21, city));
        city.setId(35);
        clientRep.save(new Client(7,"Tatiane Renata Novaes", 1, (Date)formatter.parse("24/2/1999"), 21, city));
        clientRep.save(new Client(8,"Roberto Gael Cláudio Castro", 0, (Date)formatter.parse("26/11/1999"), 21, city));
        clientRep.save(new Client(9,"Andreia Sophia Alves", 1, (Date)formatter.parse("14/8/1999"), 21, city));
        city.setId(886);
        clientRep.save(new Client(10,"Helena Silvana Drumond", 1, (Date)formatter.parse("1/11/1999"), 21, city));
        clientRep.save(new Client(11,"Alana Allana Cecília da Rocha", 1, (Date)formatter.parse("15/2/1999"), 21, city));
        clientRep.save(new Client(12,"Fabiana Giovanna Mirella Ferreira", 1, (Date)formatter.parse("25/1/1999"), 21, city));
        city.setId(918);
        clientRep.save(new Client(13,"Henrique Ruan Otávio Carvalho", 0, (Date)formatter.parse("26/9/1999"), 21, city));
        clientRep.save(new Client(14,"Caleb Severino Filipe Martins", 0, (Date)formatter.parse("2/1/1999"), 21, city));
        clientRep.save(new Client(15,"Evelyn Marina Carolina da Mota", 1, (Date)formatter.parse("22/6/1999"), 21, city));
        city.setId(931);
        clientRep.save(new Client(16,"Ester Emanuelly Pires", 1, (Date)formatter.parse("22/7/1999"), 21, city));
        clientRep.save(new Client(17,"Isadora Tânia Giovanna Caldeira", 1, (Date)formatter.parse("4/10/1999"), 21, city));
        clientRep.save(new Client(18,"Vitor Ryan Moreira", 0, (Date)formatter.parse("23/5/1999"), 21, city));
        city.setId(182);
        clientRep.save(new Client(19,"Tânia Elza Cláudia Silva", 1, (Date)formatter.parse("25/7/1999"), 21, city));
        clientRep.save(new Client(20,"Pietra Ana Sophie Moraes", 1, (Date)formatter.parse("11/5/1999"), 21, city));
        clientRep.save(new Client(21,"Otávio Kaique Nascimento", 0, (Date)formatter.parse("28/2/1999"), 22, city));
        city.setId(456);
        clientRep.save(new Client(22,"Leonardo Rodrigo da Luz", 0, (Date)formatter.parse("8/8/1999"), 23, city));
        clientRep.save(new Client(23,"Oliver Iago André Lopes", 0, (Date)formatter.parse("10/5/1999"), 24, city));
        city.setId(708);
        clientRep.save(new Client(24,"Bernardo Davi Ramos", 0, (Date)formatter.parse("23/1/1999"), 25, city));
        clientRep.save(new Client(25,"Ayla Tânia Assunção", 1, (Date)formatter.parse("15/6/1999"), 26, city));

    }

}
